//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCodeFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Calendars> Calendars { get; set; }
        public virtual DbSet<CalendarTaskSubitems> CalendarTaskSubitems { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<GroupTaskItems> GroupTaskItems { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TaskItemGroups> TaskItemGroups { get; set; }
        public virtual DbSet<TaskItems> TaskItems { get; set; }
        public virtual DbSet<TaskStatus> TaskStatus { get; set; }
        public virtual DbSet<TaskSubitems> TaskSubitems { get; set; }
        public virtual DbSet<TaskTypes> TaskTypes { get; set; }
        public virtual DbSet<TodoItems> TodoItems { get; set; }
        public virtual DbSet<UserGroupRoles> UserGroupRoles { get; set; }
        public virtual DbSet<UserNotifications> UserNotifications { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
